### ISSUE TITLE
Backslash not escaped properly for letter "a"

### ISSUE THREAD

**Issue by PureFallen** [TreeBen77/automod-regex-generator#1]
It seems that the Backslash for `/\` is not escaped properly. The expected Regex Expression would be `/\\`.
I was hoping to make this a pull request but i couldn't see where exactly in `symReplacers` that issue was caused either.

![image](https://user-images.githubusercontent.com/68307987/230978621-93daeba7-b79a-41c2-a6dc-f4ba5723d5b4.png)

**Comment by treeben77** [comment]
I've fixed the issue! Escaping the backslashes is really difficult, because it requires be to escape the backslash in the string, so it sometimes looks like this `\\\\` which can get super confusing.
