### ISSUE TITLE
Discord invite regex

### ISSUE THREAD

**Issue by Firecul** [TreeBen77/automod-regex-generator#2]
`(https?:\/\/|http?:\/\/)?(www.)?(discord.(gg|io|me|li)|discordapp.com\/invite|discord.com\/invite)\/[^\s\/]+`

Should catch most invite codes unless I'm missing some obviously

**Comment by treeben77** [comment]
it doesn't seem to be a valid rust regex, I'll rewrite it myself. you also seemed to miss at least: dsc.gg, discord.id, and id.nerrix.ovh.

and of course it's inevitable that we don't get all sites, ill make sure to state that on the site

**Comment by treeben77** [comment]
I've made the following two regexes:

third party invites:
```
(?:https?://)?(?:www\.)?(?:dsc\.gg|invite\.gg+|discord\.link|(?:discord\.(gg|io|me|li|id)))/[a-z0-9-_]+
```
offical invites and server pages:
```
(?:https?://)?(?:www.|ptb.|canary.)?(?:discord(?:app)?\.(?:(?:com|gg)/(?:invite|servers)/[a-z0-9-_]+)|discord\.gg/[a-z0-9-_]+)
```

ill add them to the website a bit later when i'm free

**Comment by Firecul** [comment]
> it doesn't seem to be a valid rust regex,

I'll be honest, I've never used rust. So I'm not sure what the differences would be. As long as it gives you a good basis then I'm still happy with what I did.

> you also seemed to miss at least: dsc.gg, discord.id, and id.nerrix.ovh.

I've never seen those used before so I'll have to go with your experience there.

**Comment by Firecul** [comment]
For the end of the regex I would personally use `[a-zA-Z0-9-_]+` to also capture uppercase letters

**Comment by treeben77** [comment]
I've added the invite link regex now :D
https://treeben77.github.io/automod-regex-generator/regexes.html#invite-links

thank you for suggesting it
