### ISSUE TITLE
Caps are still allowed somehow

### ISSUE THREAD

**Issue by Rix565** [TreeBen77/automod-regex-generator#3]
Example: if I ban the word something, writing Something will still send.

**Comment by treeben77** [comment]
I can't seem to replicate the issue:

![image](https://github.com/treeben77/automod-regex-generator/assets/77905642/f6e48a34-5834-405a-a3e0-c9960994b21e)

I'm using this regex:
```
(s|5|§|🇸)+(o|0|🇴|🅾️⭕)+(m|nn|rn|🇲|Ⓜ️)+(e|3|£|🇪)+(t|7|🇹|✝️)+(h|\|-\||#|\}\{|🇭)+(i|1|!|l|🇮|ℹ️)+(n|\|\||🇳)+(g|9|🇬)+
```

Generated with these settings enabled:
- Number Variants
- Symbol Variants
- Letter Variants 
- Emoji Variants 
- Letter Spam 
- Partial Matches 

Please follow up with more information to help me replicate your bug.

**Comment by Rix565** [comment]
Then it probably is a bug with yagpdb...

**Comment by treeben77** [comment]
If you're using the regexes for other uses, than you'd have to add the case insensitive flag into it. add this to the start of the regex:
```
(?i)
```
